export const TIMEZONE_OPTIONS = [
  { value: 'Pacific/Midway', label: 'UTC-11 — Midway Island' },
  { value: 'Pacific/Honolulu', label: 'UTC-10 — Hawaii' },
  { value: 'America/Anchorage', label: 'UTC-9 — Alaska' },
  { value: 'America/Los_Angeles', label: 'UTC-8 — Pacific Time (US)' },
  { value: 'America/Denver', label: 'UTC-7 — Mountain Time (US)' },
  { value: 'America/Phoenix', label: 'UTC-7 — Arizona' },
  { value: 'America/Chicago', label: 'UTC-6 — Central Time (US)' },
  { value: 'America/Mexico_City', label: 'UTC-6 — Mexico City' },
  { value: 'America/New_York', label: 'UTC-5 — Eastern Time (US)' },
  { value: 'America/Bogota', label: 'UTC-5 — Bogota' },
  { value: 'America/Caracas', label: 'UTC-4 — Caracas' },
  { value: 'America/Halifax', label: 'UTC-4 — Atlantic Time' },
  { value: 'America/Santiago', label: 'UTC-4 — Santiago' },
  { value: 'America/Sao_Paulo', label: 'UTC-3 — São Paulo' },
  { value: 'America/Argentina/Buenos_Aires', label: 'UTC-3 — Buenos Aires' },
  { value: 'Atlantic/Azores', label: 'UTC-1 — Azores' },
  { value: 'UTC', label: 'UTC+0 — UTC' },
  { value: 'Europe/London', label: 'UTC+0 — London' },
  { value: 'Europe/Lisbon', label: 'UTC+0 — Lisbon' },
  { value: 'Africa/Casablanca', label: 'UTC+1 — Casablanca' },
  { value: 'Europe/Paris', label: 'UTC+1 — Paris' },
  { value: 'Europe/Berlin', label: 'UTC+1 — Berlin' },
  { value: 'Europe/Amsterdam', label: 'UTC+1 — Amsterdam' },
  { value: 'Europe/Madrid', label: 'UTC+1 — Madrid' },
  { value: 'Europe/Rome', label: 'UTC+1 — Rome' },
  { value: 'Europe/Zurich', label: 'UTC+1 — Zurich' },
  { value: 'Africa/Lagos', label: 'UTC+1 — Lagos' },
  { value: 'Europe/Athens', label: 'UTC+2 — Athens' },
  { value: 'Europe/Helsinki', label: 'UTC+2 — Helsinki' },
  { value: 'Europe/Istanbul', label: 'UTC+3 — Istanbul' },
  { value: 'Africa/Cairo', label: 'UTC+2 — Cairo' },
  { value: 'Africa/Johannesburg', label: 'UTC+2 — Johannesburg' },
  { value: 'Europe/Moscow', label: 'UTC+3 — Moscow' },
  { value: 'Asia/Riyadh', label: 'UTC+3 — Riyadh' },
  { value: 'Africa/Nairobi', label: 'UTC+3 — Nairobi' },
  { value: 'Asia/Tehran', label: 'UTC+3:30 — Tehran' },
  { value: 'Asia/Dubai', label: 'UTC+4 — Dubai' },
  { value: 'Asia/Baku', label: 'UTC+4 — Baku' },
  { value: 'Asia/Kabul', label: 'UTC+4:30 — Kabul' },
  { value: 'Asia/Karachi', label: 'UTC+5 — Karachi' },
  { value: 'Asia/Tashkent', label: 'UTC+5 — Tashkent' },
  { value: 'Asia/Kolkata', label: 'UTC+5:30 — India (IST)' },
  { value: 'Asia/Kathmandu', label: 'UTC+5:45 — Kathmandu' },
  { value: 'Asia/Dhaka', label: 'UTC+6 — Dhaka' },
  { value: 'Asia/Almaty', label: 'UTC+6 — Almaty' },
  { value: 'Asia/Yangon', label: 'UTC+6:30 — Yangon' },
  { value: 'Asia/Bangkok', label: 'UTC+7 — Bangkok' },
  { value: 'Asia/Jakarta', label: 'UTC+7 — Jakarta' },
  { value: 'Asia/Ho_Chi_Minh', label: 'UTC+7 — Ho Chi Minh' },
  { value: 'Asia/Shanghai', label: 'UTC+8 — Shanghai' },
  { value: 'Asia/Hong_Kong', label: 'UTC+8 — Hong Kong' },
  { value: 'Asia/Singapore', label: 'UTC+8 — Singapore' },
  { value: 'Asia/Taipei', label: 'UTC+8 — Taipei' },
  { value: 'Asia/Kuala_Lumpur', label: 'UTC+8 — Kuala Lumpur' },
  { value: 'Asia/Manila', label: 'UTC+8 — Manila' },
  { value: 'Australia/Perth', label: 'UTC+8 — Perth' },
  { value: 'Asia/Seoul', label: 'UTC+9 — Seoul' },
  { value: 'Asia/Tokyo', label: 'UTC+9 — Tokyo' },
  { value: 'Australia/Adelaide', label: 'UTC+9:30 — Adelaide' },
  { value: 'Australia/Brisbane', label: 'UTC+10 — Brisbane' },
  { value: 'Australia/Sydney', label: 'UTC+10 — Sydney' },
  { value: 'Australia/Melbourne', label: 'UTC+10 — Melbourne' },
  { value: 'Pacific/Guam', label: 'UTC+10 — Guam' },
  { value: 'Pacific/Noumea', label: 'UTC+11 — Noumea' },
  { value: 'Pacific/Auckland', label: 'UTC+12 — Auckland' },
  { value: 'Pacific/Fiji', label: 'UTC+12 — Fiji' },
  { value: 'Pacific/Tongatapu', label: 'UTC+13 — Tonga' },
];
