// activityActions.js
export const STAFF_ACTIONS = {
  STAFF_LOGIN: "STAFF_LOGIN",
  STAFF_LOGOUT: "STAFF_LOGOUT",

  OPEN_TABLE_SESSION: "OPEN_TABLE_SESSION",
  CLOSE_TABLE_SESSION: "CLOSE_TABLE_SESSION",

  ADD_ORDER_ITEM: "ADD_ORDER_ITEM",
  REMOVE_ORDER_ITEM: "REMOVE_ORDER_ITEM",
  VOID_ITEM: "VOID_ITEM",

  APPLY_SERVICE_CHARGE: "APPLY_SERVICE_CHARGE",
};
